[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kaggle-lmsys2"
version = "0.1.0"
description = "kaggle-lmsys2"
readme = "README.md"

[tool.setuptools]
packages = ["lmsys"]